version: '3.6'

services:
  web:
    env_file:
      - ./.flaskenv
    build: .
    command: gunicorn -b 0.0.0.0:5000 api.wsgi:app
    depends_on:
      - db
    environment:
      STAGE: deveopment
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./api:/code/api
      - ./db/:/db/
    restart: always

  db:
    env_file:
      - ./.psqlenv
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
